/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import VectorImage from '../../src/images/popupuploadfile_Vector.png';
import Vector1Image from '../../src/images/popupuploadfile_Vector_1.png';
import Vector2Image from '../../src/images/popupuploadfile_Vector_2.png';
import Vector3Image from '../../src/images/popupuploadfile_Vector_3.png';
import Vector4Image from '../../src/images/popupuploadfile_Vector_4.png';
import Vector5Image from '../../src/images/popupuploadfile_Vector_5.png';
import Vector6Image from '../../src/images/popupuploadfile_Vector_6.png';
import Vector7Image from '../../src/images/popupuploadfile_Vector_7.png';
import Vector8Image from '../../src/images/popupuploadfile_Vector_8.png';
import { styled } from '@mui/material/styles';

const PopUpUploadFile1 = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  boxShadow: `4px -4px 4px rgba(0, 0, 0, 0.25)`,
  borderRadius: `15px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: '100%',
  height: `191px`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  overflow: `hidden`,
});

const Frame216 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  left: `14px`,
  top: `16px`,
});

const SelectFromYourDevice = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `500`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  margin: `0px`,
});

const X = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `18px`,
  height: `18px`,
  margin: `0px 0px 0px 48px`,
  overflow: `hidden`,
});

const Vector = styled('img')({
  height: `9px`,
  width: `9px`,
  position: `absolute`,
  left: `5px`,
  top: `5px`,
});

const Vector1 = styled('img')({
  height: `9px`,
  width: `9px`,
  position: `absolute`,
  left: `5px`,
  top: `5px`,
});

const Frame220 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  left: `36px`,
  top: `55px`,
});

const Frame217 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px`,
});

const Image1 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `24px`,
  height: `24px`,
  margin: `0px`,
  overflow: `hidden`,
});

const Vector2 = styled('img')({
  height: `18px`,
  width: `18px`,
  position: `absolute`,
  left: `3px`,
  top: `3px`,
});

const Vector3 = styled('img')({
  height: `3px`,
  width: `3px`,
  position: `absolute`,
  left: `7px`,
  top: `7px`,
});

const Vector4 = styled('img')({
  height: `11px`,
  width: `16px`,
  position: `absolute`,
  left: `5px`,
  top: `10px`,
});

const PhotoLibrary = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `12px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  margin: `0px 0px 0px 20px`,
});

const Frame218 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `20px 0px 0px 0px`,
});

const Camera = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `24px`,
  height: `24px`,
  margin: `0px`,
  overflow: `hidden`,
});

const Vector5 = styled('img')({
  height: `18px`,
  width: `22px`,
  position: `absolute`,
  left: `1px`,
  top: `3px`,
});

const Vector6 = styled('img')({
  height: `8px`,
  width: `8px`,
  position: `absolute`,
  left: `8px`,
  top: `9px`,
});

const TakePhoto = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `12px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  margin: `0px 0px 0px 20px`,
});

const Frame219 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `20px 0px 0px 0px`,
});

const File = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `24px`,
  height: `24px`,
  margin: `0px`,
  overflow: `hidden`,
});

const Vector7 = styled('img')({
  height: `20px`,
  width: `16px`,
  position: `absolute`,
  left: `4px`,
  top: `2px`,
});

const Vector8 = styled('img')({
  height: `7px`,
  width: `7px`,
  position: `absolute`,
  left: `13px`,
  top: `2px`,
});

const ChooseAFile = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `12px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  margin: `0px 0px 0px 20px`,
});

function PopUpUploadFile(props) {
  return (
    <PopUpUploadFile1 className={props.className}>
      <Frame216>
        <SelectFromYourDevice>{`Select from your device`}</SelectFromYourDevice>
        <X>
          <Vector src={VectorImage} loading="lazy" alt={'Vector'} />
          <Vector1 src={Vector1Image} loading="lazy" alt={'Vector'} />
        </X>
      </Frame216>
      <Frame220>
        <Frame217>
          <Image1>
            <Vector2 src={Vector2Image} loading="lazy" alt={'Vector'} />
            <Vector3 src={Vector3Image} loading="lazy" alt={'Vector'} />
            <Vector4 src={Vector4Image} loading="lazy" alt={'Vector'} />
          </Image1>
          <PhotoLibrary>{`Photo library`}</PhotoLibrary>
        </Frame217>
        <Frame218>
          <Camera>
            <Vector5 src={Vector5Image} loading="lazy" alt={'Vector'} />
            <Vector6 src={Vector6Image} loading="lazy" alt={'Vector'} />
          </Camera>
          <TakePhoto>{`Take photo`}</TakePhoto>
        </Frame218>
        <Frame219>
          <File>
            <Vector7 src={Vector7Image} loading="lazy" alt={'Vector'} />
            <Vector8 src={Vector8Image} loading="lazy" alt={'Vector'} />
          </File>
          <ChooseAFile>{`Choose a file`}</ChooseAFile>
        </Frame219>
      </Frame220>
    </PopUpUploadFile1>
  );
}

export default PopUpUploadFile;
