/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import { styled } from '@mui/material/styles';

const ResetPassoword1 = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: '100%',
  height: `844px`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  overflow: `hidden`,
});

const Frame118 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  left: `35px`,
  top: `247px`,
});

const NewPassword = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  margin: `0px`,
});

const Rectangle11 = styled('div')({
  backgroundColor: `rgba(242, 245, 255, 1)`,
  border: `1px solid rgba(76, 87, 229, 1)`,
  boxSizing: `border-box`,
  borderRadius: `10px`,
  height: `48px`,
  width: `320px`,
  margin: `5px 0px 0px 0px`,
});

const Frame119 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  left: `35px`,
  top: `347px`,
});

const ConfirmedPassword = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  margin: `0px`,
});

const Rectangle12 = styled('div')({
  backgroundColor: `rgba(242, 245, 255, 1)`,
  border: `1px solid rgba(76, 87, 229, 1)`,
  boxSizing: `border-box`,
  borderRadius: `10px`,
  height: `48px`,
  width: `320px`,
  margin: `5px 0px 0px 0px`,
});

const Frame80 = styled('div')({
  backgroundColor: `rgba(76, 87, 229, 1)`,
  borderRadius: `15px`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `320px`,
  height: `48px`,
  left: `35px`,
  top: `475px`,
  overflow: `hidden`,
});

const Reset = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `700`,
  fontSize: `20px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `132px`,
  top: `9px`,
});

const Frame120 = styled('div')({
  backgroundColor: `rgba(76, 87, 229, 1)`,
  borderRadius: `15px`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `320px`,
  height: `48px`,
  left: `35px`,
  top: `475px`,
  overflow: `hidden`,
});

const Reset1 = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `700`,
  fontSize: `20px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `132px`,
  top: `9px`,
});

const ResetPassword = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `700`,
  fontSize: `24px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `35px`,
  top: `112px`,
});

function ResetPassoword(props) {
  return (
    <ResetPassoword1 className={props.className}>
      <Frame118>
        <NewPassword>{`New password`}</NewPassword>
        <Rectangle11></Rectangle11>
      </Frame118>
      <Frame119>
        <ConfirmedPassword>{`Confirmed password`}</ConfirmedPassword>
        <Rectangle12></Rectangle12>
      </Frame119>
      <Frame80>
        <Reset>{`Reset`}</Reset>
      </Frame80>
      <Frame120>
        <Reset1>{`Reset`}</Reset1>
      </Frame120>
      <ResetPassword>{`Reset password`}</ResetPassword>
    </ResetPassoword1>
  );
}

export default ResetPassoword;
