/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import { styled } from '@mui/material/styles';

const PopUpLevelOfYear1 = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  boxShadow: `4px -4px 4px rgba(0, 0, 0, 0.25)`,
  borderRadius: `15px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: '100%',
  height: `191px`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  overflow: `hidden`,
});

const Frame220 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `213px`,
  left: `30px`,
  top: `21px`,
});

const Frame218 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `206px`,
  margin: `0px`,
});

const HighSchoolDiplomaOrE = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `12px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `217px`,
  margin: `0px`,
});

const Frame219 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `212px`,
  margin: `15px 0px 0px 0px`,
});

const BachelorSDegreeOrEqu = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `12px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `212px`,
  margin: `0px`,
});

const Frame2191 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `147px`,
  margin: `15px 0px 0px 0px`,
});

const MasterSDegreeOrEquiv = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `12px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `213px`,
  margin: `0px`,
});

const Frame2192 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `197px`,
  margin: `15px 0px 0px 0px`,
});

const DoctoralDegreeOrEqui = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `12px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  margin: `0px`,
});

const Frame2193 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `143px`,
  margin: `15px 0px 0px 0px`,
});

const Others = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `12px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  margin: `0px`,
});

function PopUpLevelOfYear(props) {
  return (
    <PopUpLevelOfYear1 className={props.className}>
      <Frame220>
        <Frame218>
          <HighSchoolDiplomaOrE>
            {`High school diploma or equivalent`}
          </HighSchoolDiplomaOrE>
        </Frame218>
        <Frame219>
          <BachelorSDegreeOrEqu>
            {`ฺBachelor’s degree or equivalent`}
          </BachelorSDegreeOrEqu>
        </Frame219>
        <Frame2191>
          <MasterSDegreeOrEquiv>
            {`Master’s degree or equivalent`}
          </MasterSDegreeOrEquiv>
        </Frame2191>
        <Frame2192>
          <DoctoralDegreeOrEqui>
            {`Doctoral degree or equivalent`}
          </DoctoralDegreeOrEqui>
        </Frame2192>
        <Frame2193>
          <Others>{`Others`}</Others>
        </Frame2193>
      </Frame220>
    </PopUpLevelOfYear1>
  );
}

export default PopUpLevelOfYear;
