/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import Q0012Image from 'src/assets/images/Frame77__0012.png';
import IconoirChatBubbleQueImage from 'src/assets/images/Frame77_iconoir_chat_bubble_question.png';
import { styled } from '@mui/material/styles';

const Frame771 = styled('div')({
  backgroundColor: `rgba(242, 245, 255, 1)`,
  borderRadius: `30px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: '100%',
  height: `330px`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  overflow: `hidden`,
});

const Q0012 = styled('img')({
  height: `127px`,
  width: `153px`,
  position: `absolute`,
  left: `66px`,
  top: `40px`,
});

const Frame79 = styled('div')({
  backgroundColor: `rgba(190, 190, 190, 1)`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `152px`,
  height: `48px`,
  left: `0px`,
  top: `282px`,
  overflow: `hidden`,
});

const No = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `700`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `64px`,
  top: `12px`,
});

const Frame78 = styled('div')({
  backgroundColor: `rgba(76, 87, 229, 1)`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `152px`,
  height: `48px`,
  left: `152px`,
  top: `282px`,
  overflow: `hidden`,
});

const Yes = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `700`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `61px`,
  top: `12px`,
});

const IconoirChatBubbleQue = styled('img')({
  height: `31px`,
  width: `31px`,
  position: `absolute`,
  left: `186px`,
  top: `34px`,
});

const AreYouSureYouWantToLSpan1 = styled('span')({
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `700`,
  fontSize: `20px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
});

const AreYouSureYouWantToLSpan2 = styled('span')({
  whiteSpace: `pre-wrap`,
  color: `rgba(102, 101, 101, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `500`,
  fontSize: `13px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
});

const AreYouSureYouWantToL = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: 'unset',
  fontWeight: `400`,
  fontSize: `nullpx`,
  letterSpacing: `NaNpx`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `30px`,
  top: `176px`,
});

function Frame77(props) {
  return (
    <Frame771 className={props.className}>
      <Q0012 src={Q0012Image} loading="lazy" alt={'_0012'} />
      <Frame79>
        <No>{`NO`}</No>
      </Frame79>
      <Frame78>
        <Yes>{`YES`}</Yes>
      </Frame78>
      <IconoirChatBubbleQue
        src={IconoirChatBubbleQueImage}
        loading="lazy"
        alt={'iconoir:chat-bubble-question'}
      />
      <AreYouSureYouWantToL>
        <AreYouSureYouWantToLSpan1>{`ARE YOU SURE
YOU WANT TO LOG OUT?
`}</AreYouSureYouWantToLSpan1>
        <AreYouSureYouWantToLSpan2>{`Tap YES to log out immediately.`}</AreYouSureYouWantToLSpan2>
      </AreYouSureYouWantToL>
    </Frame771>
  );
}

export default Frame77;
